version: '3.9'

services:
  ###########################
  #   traefik container
  ###########################
  traefik:
    # pull the official v2 Traefik docker image
    image: 'traefik:v2.9'
    command:
      # enable Docker in Traefik, so that it reads labels from Docker services
      - '--providers.docker=true'
      # do not expose all containers unless explicitly told so
      - '--providers.docker.exposedbydefault=false'
      # traefik will listen to incoming request on the port 8080 (HTTP)
      - '--entrypoints.web.address=:80'
    ports:
      - "80:80"
    volumes:
      # add Docker as a mounted volume, so that Traefik can read the labels of other services
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  ###########################
  #   backend container
  ###########################
  backend:
    build:
      context: ./backend_ppark
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # hostPath:containerPath:mode
      - ./backend_ppark:/backend:consistent
    # env_file:
    #   - ./backend_ppark/.env
    labels:
      # explicitly tell Traefik to expose this container
      - 'traefik.enable=true'
      # specify the rule used to match a request to this service
      - 'traefik.http.routers.backend3.rule=Host(`hilsvis_ppark_backend.localhost`) && PathPrefix(`/api`)'
      # allow request only from the predefined entry point named "web"
      - 'traefik.http.routers.backend3.entrypoints=web'
      # set port the container listens to
      - 'traefik.http.services.backend3.loadbalancer.server.port=8000'
      # enable gzip compression
      #- 'traefik.http.middlewares.backend.compress=true'
      # specify the minimum amount of bytes that must be compressed
      #- 'traefik.http.middlewares.backend.compress.minresponsebodybytes=10240'

  ###########################
  #   frontend container
  ###########################